name: Django CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Migrations & Collectstatic
      run: |
        source venv/bin/activate
        python manage.py collectstatic --no-input
        python manage.py migrate

    - name: Deploy via SSH (Copy files to server)
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "."  # You can specify the exact source files/folders here
        target: "/home/kasheetech/production/django/ci-cd"  # Target directory on your server

    - name: Restart Server via SSH (Supervisor)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          # Navigate to the project directory
          cd /home/kasheetech/production/django/ci-cd

          # Activate the virtual environment if needed (for running gunicorn or any other commands)
          source venv/bin/activate

          # Pull the latest changes (if not already done by scp-action)
          git pull origin main

          # Run migrations and collectstatic if required again
          python manage.py migrate
          python manage.py collectstatic --no-input

          # Restart the Supervisor service for Django (Gunicorn)
          sudo supervisorctl restart cicd
          