name: Django CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env

    - name: Debugging info
      run: |
        echo "============================ Debugging Info ============================"
        echo "Deploying to host: ${{ secrets.SERVER_HOST }}"
        echo "Deploying with user: ${{ secrets.SERVER_USER }}"
        echo "Using SSH Key: ${{ secrets.SERVER_SSH_KEY }}"
        echo "======================================================================="

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django Migrations & Collectstatic
      run: |
        source venv/bin/activate
        python manage.py collectstatic --no-input
        python manage.py migrate

    - name: Debugging after install and before deploy
      run: |
        echo "========================= Debugging Before Deploy ====================="
        echo "Current directory: $(pwd)"
        echo "Files in the directory:"
        ls -al
        echo "======================================================================="

    - name: Deploy via SSH (Copy files to server)
      run: |
        echo "========================= Deploying via SCP ========================="
        echo "Deploying to host: ${{ secrets.SERVER_HOST }}"
        echo "Deploying with user: ${{ secrets.SERVER_USER }}"
        echo "Using SSH Key: ${{ secrets.SERVER_SSH_KEY }}"

        scp -i ${{ secrets.SERVER_SSH_KEY }} -P 22 -r . ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/kasheetech/production/django/ci-cd

    - name: Debugging after SCP
      run: |
        echo "========================= Debugging After Deploy ====================="
        echo "Checking if files were deployed:"
        ssh -i ${{ secrets.SERVER_SSH_KEY }} -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "ls -al /home/kasheetech/production/django/ci-cd"
        echo "======================================================================="

    - name: Restart Server via SSH (Supervisor)
      run: |
        echo "========================= Restarting Supervisor ======================"
        ssh -i ${{ secrets.SERVER_SSH_KEY }} -p 22 ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /home/kasheetech/production/django/ci-cd
          source venv/bin/activate
          git pull origin main
          python manage.py migrate
          python manage.py collectstatic --no-input
          sudo supervisorctl restart cicd
        EOF
        echo "======================================================================="
