name: Django CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Create .env file
      run: |
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
        echo "DEBUG=${{ secrets.DEBUG }}" >> .env
        echo "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" >> .env
        # Add other environment variables as needed

    - name: Run Django Migrations & Collectstatic
      run: |
        python manage.py check --deploy
        python manage.py migrate
        python manage.py collectstatic --no-input

    - name: Deploy via SSH (Copy files to server)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        source: "."
        target: "/home/kasheetech/production/django/ci-cd"
        rm: true  # Remove old files before copying
        strip_components: 1

    - name: Install dependencies on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /home/kasheetech/production/django/ci-cd
          python -m venv venv || true
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

    - name: Restart Server via SSH (Supervisor)
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        script: |
          cd /home/kasheetech/production/django/ci-cd
          source venv/bin/activate
          python manage.py migrate
          python manage.py collectstatic --no-input
          sudo supervisorctl restart cicd